---
abstract: 'Rename hash keys'
author:
  - 'The following person is the author of all the files provided in this'
build_requires:
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Rename
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
resources:
  bugtracker: https://github.com/marcelgruenauer/Hash-Rename/issues
  homepage: https://github.com/marcelgruenauer/Hash-Rename
  repository: https://github.com/marcelgruenauer/Hash-Rename.git
version: 2.00
x_contributors:
  - 'Marcel Gruenauer <hanekomu@gmail.com>'
