---
abstract: 'Rename hash keys'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Rename
provides:
  Hash::Rename:
    file: lib/Hash/Rename.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Hash-Rename
  homepage: http://search.cpan.org/dist/Hash-Rename/
  repository: http://github.com/hanekomu/Hash-Rename
version: 1.100860
